package at.madlmayr.bosealarmclock.key;

public enum KeyPressValueEnum {

    PLAY, PAUSE, PLAY_PAUSE, PREV_TRACK, NEXT_TRACK, MUTE, SHUFFLE_ON, SHUFFLE_OFF, REPEAT_ONE, REPEAT_ALL, REPEAT_OFF, ADD_FAVORITE, REMOVE_FAVORITE, THUMBS_UP, THUMBS_DOWN, BOOKMARK

}
